package com.kylek.ripe.waxeye;
/*
 * Generated by the Waxeye Parser Generator - version 0.8.0
 * www.waxeye.org
 */

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum AttributesType
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    ATTRIBUTES,
    ATTRIBUTE,
    YIELD,
    YIELD_PREFIX,
    COOK_TIME,
    COOK_TIME_PREFIX,
    TIME_UNITS,
    PREP_TIME,
    PREP_TIME_PREFIX,
    OVERALL_TIME,
    OVERALL_TIME_PREFIX,
    ATTRIBUTE_SEPARATOR,
    Wsn,
    Ws,
    Pwsn,
    Pws,
    WORDS,
    WORDS_NO_BREAK,
    AMOUNT,
    NUMBER_OR_FRACTION,
    UNIT
}
