package com.kylek.ripe.waxeye;
/*
 * Generated by the Waxeye Parser Generator - version 0.8.0
 * www.waxeye.org
 */

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum IngredientsListType
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    INGREDIENTS_LIST,
    INGREDIENT,
    MEASUREMENT,
    MEASUREMENT_SEPARATOR,
    SPECIFIER,
    GENERALIZER,
    SPECIAL_DIRECTIONS,
    PRODUCT,
    PRODUCT_WORDS_NO_BREAK,
    Wsn,
    Ws,
    Pwsn,
    Pws,
    WORDS,
    WORDS_NO_BREAK,
    WORDS_NO_PARENS,
    AMOUNT,
    NUMBER_OR_FRACTION,
    UNIT
}
