package com.kylek.ripe.waxeye;
/*
 * Generated by the Waxeye Parser Generator - version 0.8.0
 * www.waxeye.org
 */

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum Type
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    RECIPE,
    TITLE,
    WORDS,
    WORDS_NO_BREAK,
    ATTRIBUTES,
    ATTRIBUTE,
    YIELD,
    YIELD_PREFIX,
    COOK_TIME,
    COOK_TIME_PREFIX,
    TIME_UNITS,
    PREP_TIME,
    PREP_TIME_PREFIX,
    OVERALL_TIME,
    OVERALL_TIME_PREFIX,
    ATTRIBUTE_SEPARATOR,
    INGREDIENTS_LIST,
    INGREDIENTS_PREFIX,
    INGREDIENT,
    MEASUREMENT,
    AMOUNT,
    UNIT,
    SPECIFIER,
    GENERALIZER,
    NUMBER_OR_FRACTION,
    SPECIAL_DIRECTIONS,
    PRODUCT,
    DIRECTIONS,
    DIRECTIONS_HEADER,
    DIRECTIONS_TEXT,
    Wsn,
    Ws,
    Pwsn,
    Pws
}
